### ISSUE TITLE
Visiting a secured page while logged out, should redirect to login then bounce back

### ISSUE THREAD

**Issue by ghost** [bravecollective/forums#15]
Repro: Visit https://forums.bravecollective.net/pve/52efec4958b7001ea2d7d8f0 in a browser that is not logged into the forums

Expected: a redirect to something like `https://forums.bravecollective.net/authorize/?bounce=%2Fpve%2F52efec4958b7001ea2d7d8f0` that redirects to the desired page after login (or fails again due to permissions.)

Actual: default 404 page

**Comment by amcgregor** [comment]
Very specifically the `raise HTTPNotFound()` calls need to be replaced with `raise HTTPForbidden()`; this should automatically perform the login redirection magic.

**Comment by amcgregor** [comment]
Done.  You'll still get a 404 if, after logging in, you still don't have permission to access that link.
