### ISSUE TITLE
Enhancement: Anchor elements for individual posts and responses.

### ISSUE THREAD

**Issue by mrogaski** [bravecollective/forums#17]
It would be extremely useful to have anchor elements for individual posts and responses, to allow direct linking to a response (instead of the thread itself).  

Providing anchor elements would also allow linking to the first new response (posted since last view of the thread) fro the Active Discussions and Latest Discussions lists.

**Comment by amcgregor** [comment]
The anchors already exist, I just need to provide some helpful way to jump to them.

**Comment by amcgregor** [comment]
Hmm; interesting glitch with the anchors and the fixed navigation bar.  Might simply make it un-fixed to avoid the problem of linking to a reply that is completely obscured.  Temporarily, link to the anchor of the comment before the one you are actually interested in.  XD

https://forums.bravecollective.net/a/52f03c2458b7001ea2d7d95f#52f1224e58b70033f0a0da1f
