### ISSUE TITLE
Submitting a reply on Firefox is broken

### ISSUE THREAD

**Issue by kiu** [bravecollective/forums#19]
When submitting a reply in Firefox (Ubuntu+Windows), the submit button will stay grayed out forever and show the comment even though it was actually submitted.

You need to manually reload the page to see your comment on the page.

But even after reloading the page and seeing your comment on the page, the textinput still has your last comment and a grayed out button.

You need to manually load the page (not reload) to get back a working thread.

**Comment by amcgregor** [comment]
Refreshing and not having the form reset to its default values is a bug in Firefox.  There are currently several semi-random issues surrounding the reply functionality.  For example, if you click the 'comment' link at the top to jump down, submitting the form will behave badly.  If you use any anchor (to jump to a reply or jump to the comment box) the push events will appear to duplicate the page if someone else comments while you are viewing a thread.  Etc.
