### ISSUE TITLE
sensitive topic forums by auth

### ISSUE THREAD

**Issue by noilek** [bravecollective/forums#21]
Hi!

We have some classes of pilots that don't fall under a title or role in BNI that need access to "hidden" or sensitive forums, ie, cap pilots, etc.

Do you have a current plan for managing such forums - ie, how to tag them as such and allow allocation of the tag to the members?

I work at a place that deals in highly sensitive information and the way we do it seems adaptable to what we've got currently in core with some minor extensions.

Basically there are users, groups, tags, and roles  
- Users belong to groups, and groups have tags.  
- The group represents some sort of functional role (ie, moderator, admin, cap pilot, FC, DI, Dojo Sensei).
- The tags represent some sort of information barrier (public, future doctrine, war planning, capital fleet planning).
- Roles are read, write (which implies read), manager (which implies read and write)

All users have to belong to at least one group.  When trying to access a piece of information we compare the tags on the information with the full set of tags associated with all the groups the member belongs in.  If the informations set of tags is a proper subset of the users tags, then they get access to the information.  They get access to the minimum set of roles intersection of the shared tags between the user and the information have (ie, if every tag has at least write attached for the user, then the user can add information).

Manager role implies the ability to add or remove tags for which they have manager role for, and the ability add/remove users from groups for which they have manager role for all tags associated with the group.

In the forums you could imagine this taking the form of all first class concepts having a set of tags attached, primarily associated with the Categories & Forums.  Read implies you can see the collection of forums or threads in the forum, write implies you can post into the forum, manager implies you can moderate and grant / revoke the tag from people.

I anticipate this would require at least one UI at first - the UI for managing users tags for managers.  They would be able to search the space of characters, and finding one, they can grant it tags and roles in those tags.  Then revoke the tags for users they've already granted it.

An additional UI would be for the tagging of categories and forums, but this could be managed by the sys admin of the forum directly in mongo at first.

**Comment by noilek** [comment]
N.B., I know the forums have a read/write/moderate tag attached to them already

**Comment by lizthegrey** [comment]
This is actually more of a Core groups request rather than a forum-specific request.

**Comment by amcgregor** [comment]
There is not a user/group/role separation.  There are only groups.  Each group in Core defines a singular tag, the ID of the group, and each application registered with Core defines a set mask of tags it wants to hear about.  The latter point is important to reduce the overhead of evaluating the ACL rules per-user per-application.

See: https://github.com/bravecollective/core/wiki/Groups

We use dot-notation in the tags to "group" similar or related groups together, for example `fc` and `fc.trial`.  The Mumble ICE authentication hook automatically constructs two additional groups during user log-in, `corporation-ID` and `alliance-ID` where ID is the EVE integer identifier.  For Mumble the remaining magic happens internally in Mumble's own per-channel ACL rules.

The forums take a different approach: each forum has three attributes related to authorization: `read`, `write`, and `moderate`, each defining a tag which would grant that level of access.  (If read or write is None then anyone may read and/or write, i.e. a public forum.)  As you say, higher privileges imply lower privileges.

Need multiple tags, like the FC example?  Use multiple logical Groups.  The permissions those groups imply is left up as an exercise for the application consuming the authentication information from Core.  Each group is owned by a Core user, allowing group organizers to construct and manage their Groups and the ACLs involved (i.e. whitelist, role, title, API key type, available mask, etc.)

This is definitely a Core ticket, though, not Forums.

**Comment by amcgregor** [comment]
Just a quick note to follow up with; I, too, had some pretty wild security requirements at work, back in the day.  The result was the following and encouraged me to swear off complicated authorization schemes forever:

![screen shot 2010-07-25 at 1 04 02 am](https://f.cloud.github.com/assets/76750/2234171/2fe0cde0-9b34-11e3-8948-14dcd779c56b.PNG)

**Comment by noilek** [comment]
Yes sorry, I think the proposal clouded the problem I was trying to bring out. Group membership is computed by acls, which is derived from API verified facts. However there are classes that are not strictly api verifiable. An example is the set of authenticated and approved capital pilots. We don't want this list to be public information, so a title is likely not appropriate. Nor likely a role. 

How would one create a forum for only the capital pilots Arik has approved to participate?

Hence putting this in forums

**Comment by amcgregor** [comment]
The way the current capital group is implemented: as a whitelist.

The ACL rules for a Group could determine access based on the current outside temperature, phase of the moon, or anything else you could possibly want.  They are not restricted to only in-game facts.

Edited to add: of course, the actual ACL ruleset for the capital group is a little fancier than that.  It ensures alliance membership, API key type (account) and mask, and in the future will even check your assets to make sure you own something akin to a capital.

**Comment by lizthegrey** [comment]
You can make a Group just whitelist by individual characters, and have a management interface for Arik to edit the ACL of a group. Or even have the 'manager' of a group be an acl itself to determine who can edit the group :)
