### ISSUE TITLE
"Start Discussion" UI Issues

### ISSUE THREAD

**Issue by amcgregor** [bravecollective/forums#44]
(Moved from the [Core issue tracker](/bravecollective/core/issues/93).)

The UI for "start discussion" looks like this:

![2014-02-26-152508_1366x768_scrot](https://f.cloud.github.com/assets/218734/2275163/af9dfe9c-9f24-11e3-9a96-fcb1af18efa8.png)

Specifically, the top "Start Discussion" button means "actually post", while the bottom one means "hide the post UI, even if you've typed something"; since there's no auto-refresh, the second one tricked me into hitting refresh, hoping to see my new post, thus losing my actual post text.

Ideally the two buttons should look somehow visually distinct, or the top button should be green and say "Post" and the bottom one should be like "[Show|Hide] Post Editor" or something.

**Comment by amcgregor** [comment]
Indeed; this UI atom hasn't been changed since it was originally written and posts being eaten by mis-clicks and refreshes is a common problem.  The correct solution would be to do what I mentioned on mumble long ago: move all thread creation, reply, and editing (i.e. "comment") forms into a modal popover.

**Comment by jboning** [comment]
Here's what I have hacked up. Interested in design ideas; it feels like it needs a more substantial rework than just stuffing the form in a modal.

![](https://dl.dropbox.com/s/bfgymq47pmgfms8/Screenshot%202014-03-04%2002.46.08.png)

**Comment by amcgregor** [comment]
From the core service, this is more along the lines of what I had in mind:

![screen shot 2014-03-04 at 8 43 40 am](https://f.cloud.github.com/assets/76750/2321414/0b2e4b22-a3a3-11e3-8215-21c522b41d13.png)

**Comment by kiu** [comment]
While the UI discussion is ongoing, can we deploy https://github.com/bravecollective/forums/pull/62 to production as an interim solution?
