### ISSUE TITLE
need better tolerance for bad bbcode

### ISSUE THREAD

**Issue by jboning** [bravecollective/forums#45]
Currently, the forums 500 on some forms of bad markup. We should fail gracefully instead, so that threads with bad markup are still readable.

Discovered this via:

> Need [spoilers] desperately.

There is similar badness if you throw "[system]" in the middle of some text with no value.

**Comment by amcgregor** [comment]
Should capture the exception, string-ify it, show the exception message in a red footer of the message and show the raw message content instead, IMHO.
