### ISSUE TITLE
Subscriptions feature.

### ISSUE THREAD

**Issue by amcgregor** [bravecollective/forums#55]
**As a** user
**I want to** subscribe to threads (topics)
**So I** can stay up to date with discussions that interest me

**Given** an authorized user.
**And** a thread that is of interest.
**When** the user subscribes to the thread.
**Then** the subscription should be recorded.
**And** the thread appears on the dashboard as a subscription.

**Given** a subscribed thread.
**And** an authorized user.
**When** a subscribed thread is updated.
**Then** the thread should move to the top of the subscription list.
**And** the thread should indicate new activity.

**Comment by IcyMidnight** [comment]
Bonus feature:
Given a subscribed thread,
when a subscribed thread is updated,
then an email should be sent to the user
but only if an email has not been sent since the last time the user read the thread.

**Comment by amcgregor** [comment]
I'd make that configurable: 'how often do you want e-mails' with immediate, daily, weekly, or never.  There would also be several classes of e-mail:
- Reply to a thread you started.
- Reply to a thread you've subscribed to.  (Replying to a thread would automatically subscribe.)
- Mentions.  (Because yes, if people quote properly, we can do this.)

The daily/weekly options would be activity summaries.  (Which would get in to the realm of aggregate queries…)  Optionally include text of the reply, and/or for the summaries include the "top voted" reply since you last visited the thread.
