### ISSUE TITLE
linting

### ISSUE THREAD

**Issue by jboning** [bravecollective/forums#61]
I cannot hold the style guidelines in my head. Some automated support would really help. I'll look into configuring something (flake8?).

**Comment by amcgregor** [comment]
If you can configure it to wrap at 120 columns instead of 80 or 72 or whatever PEP8 says, epic.  There are additionally a few other odd exceptions to PEP8's historical silliness.  One key item is that whitespace indentation level to the same indentation level as the previous line is not "trailing space" and thus should not be removed.  (Several reasons, notably to preserve the ability to copy/paste chunks of code into the REPL shell.)

**Comment by amcgregor** [comment]
Oh, also this wiki and the three main sub-pages outline the basis for the style, philosophy, and Git management process: https://github.com/marrow/marrow.github.com/wiki

**Comment by jboning** [comment]
Take a look at ebe03a42c725fa6c5dd85bb84d991110b42b1bc1. Configuration for flake8, and fixing a bunch of problems (both style inconsistencies and real errors). Outstanding lint warnings:

```
./startup.py:41:1: F401 'web' imported but unused
./startup.py:42:1: F401 'Controller' imported but unused
./startup.py:42:1: F401 'cache' imported but unused
./startup.py:42:1: F401 'http' imported but unused
./startup.py:42:1: F401 'request' imported but unused
./startup.py:42:1: F401 'response' imported but unused
./startup.py:42:1: F401 'session' imported but unused
./transfer.py:22:121: E501 line too long (141 > 120 characters)
./transfer.py:31:121: E501 line too long (131 > 120 characters)
./brave/forums/auth/model.py:8:121: E501 line too long (150 > 120 characters)
./brave/forums/component/comment/model.py:5:121: E501 line too long (143 > 120 characters)
./brave/forums/component/thread/model.py:9:121: E501 line too long (167 > 120 characters)
./brave/forums/component/thread/model.py:34:17: E701 multiple statements on one line (colon)
./brave/forums/component/thread/model.py:35:16: E701 multiple statements on one line (colon)
./brave/forums/component/thread/model.py:36:16: E701 multiple statements on one line (colon)
./brave/forums/component/thread/model.py:37:14: E701 multiple statements on one line (colon)
./brave/forums/util/__init__.py:44:121: E501 line too long (125 > 120 characters)
./brave/forums/util/__init__.py:45:121: E501 line too long (125 > 120 characters)
./brave/forums/util/__init__.py:51:121: E501 line too long (140 > 120 characters)
./brave/forums/util/__init__.py:52:121: E501 line too long (153 > 120 characters)
./brave/forums/util/__init__.py:53:121: E501 line too long (128 > 120 characters)
./brave/forums/util/tags.py:38:33: E211 whitespace before '('
./brave/forums/util/tags.py:38:48: E211 whitespace before '['
./brave/forums/util/tags.py:40:26: E211 whitespace before '('
./brave/forums/util/tags.py:40:53: E211 whitespace before '['
./brave/forums/util/tags.py:62:29: E211 whitespace before '['
./brave/forums/util/tags.py:70:29: E211 whitespace before '('
./brave/forums/util/tags.py:70:60: E211 whitespace before '['
./brave/forums/util/tags.py:71:20: E211 whitespace before '('
./brave/forums/util/tags.py:72:23: E211 whitespace before '('
./brave/forums/util/tags.py:72:48: E211 whitespace before '['
./brave/forums/util/tags.py:73:22: E211 whitespace before '('
./brave/forums/util/tags.py:73:44: E211 whitespace before '['
./brave/forums/util/tags.py:77:28: E211 whitespace before '['
./brave/forums/util/tags.py:81:29: E211 whitespace before '('
```

It's not very happy with the marrow stuff, and I already removed as much extra whitespace from that as seemed reasonable. Those lint rules seem otherwise worthwhile, though, so I'd feel bad about disabling them. Not sure what to do on this point.

**Comment by amcgregor** [comment]
The "whitespace before" rules can suck it, as can "multiple statements on one line" if that line is less than 120 characters.  Sometimes an if/return or if/continue just makes sense as a single line.  All warnings in startup.py can be ignored as it's a local scope template for an interactive shell; it uses nothing it imports directly, basically, it just sets it up for you to use interactively later.

It comes down to the only thing that worries me out of that whole list is > 120 character lines.

**Comment by amcgregor** [comment]
See also my techblog post from work entitled: [Your code style guide is crap, but still better than nothing.](https://web.archive.org/web/20130813163534/http://tech.matchfwd.com/your-code-style-guide-is-crap-but-still-better-than-nothing/)  (Make special note of the purpose of PEP8 listed there.)

**Comment by jboning** [comment]
a6e52fc570453c7dcc94f32968f9a593e3180885 adds ignores for setup.py and the "whitespace before" rules. Some long lines left.
