### ISSUE TITLE
User theme bug (negligible importance)

### ISSUE THREAD

**Issue by IgnisH** [bravecollective/forums#67]
Ran into this issue: That if you are using the " Nicen Jehr(dark)" user theme, and you choose to preview your text, it changes the background color of the textbox to black(the same color of the text.) This applies for both typing new, and editing older posts.  

Recreation methods
1. open forum with Google Chrome( mine at work is:Version 33.0.1750.146 m)
2. Set theme to "Nicen Jehr(dark)"
3. Go to a post and type nonsense
4. Click preview (You'll see nothing but dark)
5. You have to highlight to see the text. 

Like I said, it's negligible, just the default theme is blinding, and the "Alltrue" doesn't have enough contrast (only my opinion)

**Comment by jboning** [comment]
This might have been a bug introduced by my comment-editing change. I'll try to take a look later tonight. If it's my fault, I'll fix it to what it was before; if it's not, I'll fix it to something that seems reasonable.
