### ISSUE TITLE
Style Guide does not show when posting a new thread

### ISSUE THREAD

**Issue by DodoStek** [bravecollective/forums#69]
Title says it all. Tested with both empty and non-empty text box, whenever you switch to the 'Style Guide'-tab, there is nothing.

**Comment by amcgregor** [comment]
![screen shot 2014-03-18 at 10 28 04 am](https://f.cloud.github.com/assets/76750/2448705/998bbfe2-aea9-11e3-9b9f-df0e85c257c0.png)

Could you provide some additional details?  Browser?  Operating system?

**Comment by DodoStek** [comment]
Of course, I am new to Github and software development, so that's why the information could have been incomplete.

Browser: Google Chrome.
OS: Windows 7 SP 1 64-bit

Picture:
![image](https://f.cloud.github.com/assets/6987408/2450092/1e1ca060-aeb8-11e3-8528-c310dbecd387.png)

**Comment by amcgregor** [comment]
Could you do me a favour?  Open a new tab, right-click anywhere on a blank part of the page, select "Inspect Element", then click the "Console" word at the top of the panel that appears.  Once there, navigate to a forum and attempt to show the style guide.

Please copy any text produced in the console log and attach to this ticket.

I have tested in Chrome and it appears to work, however SOUND is utilizing a slightly different codebase than BRAVE, and as such you may have to pester June.
