### ISSUE TITLE
Posts in Corporate section visible across multiple corporations

### ISSUE THREAD

**Issue by mrogaski** [bravecollective/forums#79]
Posts from members of other corporations in the alliance are visible in the Corporate board.  This has been the case since the forums went live, but it appears no one has added an issue ticket for it yet.

https://forums.bravecollective.net/c/52f0e26b58b70033f0a0d9e6

**Comment by jboning** [comment]
Closing as a configuration problem on the old brave forums. If you encounter a similar problem in the new forums, the best place to report it is probably the IT jabber channel.
